In [1]:
!python --version

Python 3.6.10 :: Anaconda, Inc.


In [5]:
!pip --version

pip 20.0.2 from D:\Anaconda3\envs\quanap5\lib\site-packages\pip (python 3.6)



In [9]:
!pip list

Package                       Version            
----------------------------- -------------------
-pencv-python                 4.2.0.34           
absl-py                       0.9.0              
alabaster                     0.7.12             
argh                          0.26.2             
astor                         0.8.1              
astroid                       2.4.0              
atomicwrites                  1.4.0              
attrs                         19.3.0             
autopep8                      1.4.4              
awscli                        1.18.46            
Babel                         2.8.0              
backcall                      0.1.0              
bcrypt                        3.1.7              
bleach                        3.1.4              
botocore                      1.15.46            
cachetools                    4.1.0              
certifi                       2020.4.5.2         
cffi                          1.14.0             


In [12]:
import torch

In [15]:
x = torch.empty(5,3)
x = torch.rand(5,3)
x

tensor([[0.6835, 0.9408, 0.1411],
        [0.3489, 0.3388, 0.3836],
        [0.2416, 0.6776, 0.5406],
        [0.2923, 0.9687, 0.3793],
        [0.8539, 0.3131, 0.2004]])

In [18]:
x = torch.zeros(5,3, dtype=torch.long)
x

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])

In [21]:
x = torch.Tensor(5,3)
x

tensor([[1.0286e-38, 1.0653e-38, 1.0194e-38],
        [8.4490e-39, 1.0469e-38, 9.3674e-39],
        [9.9184e-39, 8.7245e-39, 9.2755e-39],
        [8.9082e-39, 9.9184e-39, 8.4490e-39],
        [9.6429e-39, 1.0653e-38, 1.0469e-38]])

In [23]:
x = torch.ones(5,3)
x

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

In [25]:
y = torch.randn_like(x, dtype=torch.double)
y

tensor([[ 0.3055,  0.0667,  0.0845],
        [ 1.5148,  0.0148, -0.4818],
        [ 0.0348,  1.1182, -0.2899],
        [ 0.3156,  1.6057,  0.1547],
        [ 0.6959,  0.8244, -0.2427]], dtype=torch.float64)

In [28]:
#y.shape
y.size()

torch.Size([5, 3])

In [31]:
y = torch.rand(5,3)
y

tensor([[0.4504, 0.6700, 0.7721],
        [0.9657, 0.9377, 0.3586],
        [0.3139, 0.7581, 0.7080],
        [0.1821, 0.2854, 0.4782],
        [0.8694, 0.7459, 0.2605]])

In [34]:
z = x + y
z

tensor([[1.4504, 1.6700, 1.7721],
        [1.9657, 1.9377, 1.3586],
        [1.3139, 1.7581, 1.7080],
        [1.1821, 1.2854, 1.4782],
        [1.8694, 1.7459, 1.2605]])

In [36]:
z = torch.add(x, y)
z

tensor([[1.4504, 1.6700, 1.7721],
        [1.9657, 1.9377, 1.3586],
        [1.3139, 1.7581, 1.7080],
        [1.1821, 1.2854, 1.4782],
        [1.8694, 1.7459, 1.2605]])

In [38]:
y.add_(x)
y

tensor([[2.4504, 2.6700, 2.7721],
        [2.9657, 2.9377, 2.3586],
        [2.3139, 2.7581, 2.7080],
        [2.1821, 2.2854, 2.4782],
        [2.8694, 2.7459, 2.2605]])

In [40]:
a = torch.rand(5,3)
a

tensor([[0.6595, 0.0412, 0.8348],
        [0.7511, 0.4735, 0.8702],
        [0.8471, 0.6389, 0.3288],
        [0.5760, 0.9777, 0.1038],
        [0.8509, 0.0539, 0.4989]])

In [42]:
b = torch.rand(5,3)
b

tensor([[0.4964, 0.0440, 0.0904],
        [0.3790, 0.4620, 0.9912],
        [0.4569, 0.8562, 0.4714],
        [0.6402, 0.5783, 0.6148],
        [0.3696, 0.7687, 0.7746]])

In [44]:
c= a + b
c

tensor([[1.1559, 0.0852, 0.9252],
        [1.1301, 0.9355, 1.8614],
        [1.3040, 1.4951, 0.8002],
        [1.2162, 1.5560, 0.7186],
        [1.2205, 0.8226, 1.2736]])

In [47]:
c1 = torch.empty(5,3)
torch.add(a, b, out=c1)
c1

tensor([[1.1559, 0.0852, 0.9252],
        [1.1301, 0.9355, 1.8614],
        [1.3040, 1.4951, 0.8002],
        [1.2162, 1.5560, 0.7186],
        [1.2205, 0.8226, 1.2736]])

In [49]:
x = torch.rand(4,4)
x

tensor([[0.7650, 0.1725, 0.7977, 0.7383],
        [0.4453, 0.1572, 0.3330, 0.8084],
        [0.9180, 0.9416, 0.8047, 0.7858],
        [0.8599, 0.3892, 0.7368, 0.3644]])

In [54]:
y=x.view(16)
y
y.shape

torch.Size([16])

In [56]:
y = x.view(-1,8)
y

tensor([[0.7650, 0.1725, 0.7977, 0.7383, 0.4453, 0.1572, 0.3330, 0.8084],
        [0.9180, 0.9416, 0.8047, 0.7858, 0.8599, 0.3892, 0.7368, 0.3644]])

In [58]:
x

tensor([[0.7650, 0.1725, 0.7977, 0.7383],
        [0.4453, 0.1572, 0.3330, 0.8084],
        [0.9180, 0.9416, 0.8047, 0.7858],
        [0.8599, 0.3892, 0.7368, 0.3644]])

In [61]:
y = x.numpy()
y

array([[0.7650092 , 0.17250448, 0.79767835, 0.7382782 ],
       [0.44525158, 0.15716732, 0.33301753, 0.808425  ],
       [0.9179664 , 0.9415721 , 0.8047325 , 0.7858386 ],
       [0.859873  , 0.3891738 , 0.73680747, 0.36438388]], dtype=float32)

In [63]:
y[0,0]

0.7650092

In [65]:
import numpy as np

In [68]:
a = np.ones(3)
a

array([1., 1., 1.])

In [70]:
b = torch.from_numpy(a)
b

tensor([1., 1., 1.], dtype=torch.float64)

In [73]:
has_device = torch.cuda.is_available()
has_device

True

In [79]:
if has_device:
    device = torch.device("cuda")
    y = torch.ones_like(x, device= device)
    x = x.to(device)
    z= x+y
    print(z)
    

tensor([[1.7650, 1.1725, 1.7977, 1.7383],
        [1.4453, 1.1572, 1.3330, 1.8084],
        [1.9180, 1.9416, 1.8047, 1.7858],
        [1.8599, 1.3892, 1.7368, 1.3644]], device='cuda:0')


In [85]:
torch.is_tensor(a)

False

In [101]:
torch.zeros(3, 3, dtype=torch.int).dtype

torch.int32

In [123]:
# torch.as_tensor(data, dtype = None, device = None) --> tensor
# Parametter:
#      data (array_like): gia tri khoi tao cua tensor. Co the la mot list, mot tuple, mot array of numpy
#      dtype (torch.dtype, tuy chon): kieu du lieu mong muon tra ve cua tensor. Mac dinh = None thi kieu du lieu se dc tham chieu theo kieu cua data khoi tao.
#      device (torch.device, tuy chon): cpu hay gpu se dc dung de luu tru tensor tra ve. Mac dinh la = None thi device hien hanh dc su dung.


a = np.array([1, 2, 3])
t = torch.as_tensor(a, device= torch.device('cuda'))
t

tensor([1, 2, 3], device='cuda:0', dtype=torch.int32)