In [1]:
# TORCH.TENSOR
# la ma tran nhieu chieu chua cac thanh phan co kieu du lieu la  float, double, long,....
# moi khi khoi tao tensor voi torch.tensor thi se luon luon copy data.
# Neu chung ta da co tensor data va chi muon thay doi tham so requires_grad thi chi su dung "require_grad_(gia tri)"" hoac "detach()"" de tranh viec copy.
import torch

In [11]:
# vi du 01:
x=torch.tensor(2.0, requires_grad=False)
print(x.requires_grad) #nen in ra True
# thay doi thuoc tinh "require_grad"
x.requires_grad_(True)
print(x.requires_grad) #ne in ra False

False
True


In [12]:
y = torch.exp(x)
y

tensor(7.3891, grad_fn=<ExpBackward>)

In [16]:
y.backward()

In [17]:
x.grad

tensor(7.3891)

In [6]:
# vi du 02:
x = torch.ones(2,2, requires_grad = True)
x

tensor([[1., 1.],
        [1., 1.]], requires_grad=True)

In [7]:
# thuec hien mot pgep tinh tren tensor vua tao ra.
y = x +2
print(y)

tensor([[3., 3.],
        [3., 3.]], grad_fn=<AddBackward0>)


In [8]:
# Vi y la ket qua  cua phep tinh toan dua tren tensor x voi thuoc tinh "require_grad = True" nen
# y se chua "grad_fn" nhu thay trong ket qua in ra phia tren hoac la
print(y.grad_fn)


In [9]:
# vi du 03: them mot phep toan phuc tap hon
z = y * y *3
out = z.mean()
print(z, out)

tensor([[27., 27.],
        [27., 27.]], grad_fn=<MulBackward0>) tensor(27., grad_fn=<MeanBackward0>)


In [10]:
# "require_grad_()"" dung de thay doi gia tri cua thuoc tinh "requires_grad". Mac dinh la False.
a = torch.randn(2,2)
a = ((a*3)/(a-1))
print(a.requires_grad)
a.requires_grad_(True)
print(a.requires_grad)

False
True
